export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";

export const METRICS_DATA_RECEIVED = "EVENT/METRICS_DATA_RECEIVED";
export const NEW_MEASUREMENTS_RECEIVED = "EVENT/NEW_MEASUREMENT_DATA_RECEIVED"
export const METRICS_MEASUREMENTS_RECEIVED = "EVENT/METRICS_MEASUREMENTS_RECEIVED";
